'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { usePathname } from 'next/navigation'
import Logout from '../../components/Logout'
import { useRouter } from 'next/navigation'

import Link from 'next/link'
import './style/style.css'



const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'JWT',
  description: 'Generated by Ajay',
}

export default function RootLayout({
  
  children,
}: {
  children: React.ReactNode
}) {
const pathname = usePathname()

const router = useRouter();
const Clear = ()=>{
  Logout();
router.push('/signup');

}
  

  return (
    <html lang="en">
      <body>
        <>
        {pathname!=='/'?
    <ul className='navbar'>
      <li>
        <Link href={'/login'}>LOGIN</Link>
      </li>
      <li>
        <Link href={'/signup'}>SIGN UP</Link>
      </li>
    </ul>:<ul className='navbar'>
      <li style={{color:'white'}}>
       AJAY
      </li>
      <button onClick={Clear} id='btn'>LOGOUT</button>
    </ul>
     
}
        {children}
        </>
        </body>
    </html>
  )
}
