'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { usePathname } from 'next/navigation'

import Link from 'next/link'
import './style/style.css'


const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'JWT',
  description: 'Generated by Ajay',
}

export default function RootLayout({
  
  children,
}: {
  children: React.ReactNode
}) {
const pathname = usePathname()

  

  return (
    <html lang="en">
      <body>
        <>
        {pathname!=='/'?
    <ul className='navbar'>
      <li>
        <Link href={'/login'}>LOGIN</Link>
      </li>
      <li>
        <Link href={'/signup'}>SIGN UP</Link>
      </li>
    </ul>:<ul className='navbar'>
      <li style={{color:'white'}}>
       HOME
      </li>
      <button id='btn'>LOGOUT</button>
    </ul>
     
}
        {children}
        </>
        </body>
    </html>
  )
}
