
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import './style/style.css'

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'JWT',
  description: 'Generated by Ajay',
}

export default function RootLayout({
  
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <>
        <nav>
          <ul className='navbar'>
            <li>
              <Link href={'/'}>LOGIN</Link>
              </li>
            <li>
              <Link href={'/signup'}>SIGN UP</Link>
              </li>
          </ul>
        </nav>
        {children}
        </>
        </body>
    </html>
  )
}
